// Copyright (C) Force67 <github.com/Force67>.
// For licensing information see LICENSE at the root of this distribution.
#include "symbol_table.h"
#include <cstdio>

namespace refl {

namespace {
cl::opt<std::string> JsonExportFile("json-export",
                                   cl::desc("Export symbol table as json"),
                                   cl::value_desc("filename"),
                                   cl::init("symbols.json"));
cl::opt<std::string> HeaderExportFile("header-export",
                                   cl::desc("Export symbol table as c++ header"),
                                   cl::value_desc("filename"),
                                   cl::init("symbols.h"));

FILE* MakeFile(std::string_view path) {
  FILE* file{};
#if defined(OS_WIN)
  fopen_s(&file, path.data(), "wb");
#else
  file = fopen(path.data(), "wb");
#endif
  return file;
}
}  // namespace

void SymbolTable::AddSymbol(const std::string& name, const std::string* signature) {
  storage_.emplace_back(std::move(name), signature ? std::move(*signature) : "");
}

void SymbolTable::AddPrivateFile(const std::string& name) {
  files_.push_back(name);
}

void SymbolTable::ExportJson() {
  if (FILE* fptr = MakeFile(JsonExportFile)) {
    fprintf(fptr, "{\"hooks\":[\n");
    for (Node& sym : storage_) {
      fprintf(fptr, "{\"name\":\"%s\", \"address\":0},\n", sym.name.c_str());
    }
    fprintf(fptr, "]}");
    fclose(fptr);
  }
}

void SymbolTable::ExportHookHeader() {
  if (FILE* fptr = MakeFile(HeaderExportFile)) {
    fprintf(fptr, "#pragma once\n\n//Autogenerated by gamerefr (c) Force67\n\n");
    // set up extern bindings
    for (Node& sym : storage_) {
      if (!sym.signature.empty()) {
        fprintf(fptr, "extern %s%s;\n", sym.name.c_str(), sym.signature.c_str());
      } else {
        fprintf(fptr, "extern %s;\n", sym.name.c_str());
      }
    }
    // set up overrides
    for (Node& sym : storage_) {
    }

    fclose(fptr);
  }
}
}  // namespace refl